
name: Download Release and Create Archive

on:
  workflow_dispatch:
  push:

jobs:
  download-and-archive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch the latest release
        id: fetch_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/latest")
          LATEST_RELEASE_URL=$(echo $response | jq -r '.zipball_url')
          RELEASE_NOTES=$(echo $response | jq -r '.body')
          echo "LATEST_RELEASE_URL=$LATEST_RELEASE_URL" >> $GITHUB_OUTPUT
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_OUTPUT
          echo "$RELEASE_NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          echo "Latest Release URL: $LATEST_RELEASE_URL"
          echo "Release Notes: $RELEASE_NOTES"

      - name: Download the latest release
        run: |
          curl -L ${{ steps.fetch_release.outputs.LATEST_RELEASE_URL }} -o source.zip
          unzip source.zip
          rm source.zip

      - name: Create Archive
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'processed_release.zip'
          exclusions: '*.git* *.DS_Store'

      - name: List files for verification
        run: |
          ls -la

      - name: Print release notes
        run: |
          echo "Release Notes:"
          echo "${{ steps.fetch_release.outputs.RELEASE_NOTES }}"

      - name: Upload processed release as artifact
        uses: actions/upload-artifact@v2
        with:
          name: processed-release
          path: processed_release.zip
      
      - name: Get session token
        env:
          ADOBE_API_URL: ${{ secrets.ADOBE_API_URL }}
          ADOBE_CLIENT_ID: ${{ secrets.ADOBE_CLIENT_ID }}
          ADOBE_CLIENT_SECRET: ${{ secrets.ADOBE_CLIENT_SECRET }}
        run: |
          curl -X POST \
          -u 'VKIMCVQ2ZN:78c24c7ab3ba4283b72859147dbbc73581fdf114' \
          -H 'Content-Type: application/json' \
          -d '{ "grant_type" : "session" }' \
          https://commercedeveloper-sandbox-api.adobe.com/rest/v1/app/session/token
          
          
