
name: Download Release and Create Archive

on:
  workflow_dispatch:
  push:

jobs:
  download-and-archive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch the latest release
        id: fetch_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/latest")
          LATEST_RELEASE_URL=$(echo $response | jq -r '.zipball_url')
          RELEASE_NOTES=$(echo $response | jq -r '.body')
          echo "LATEST_RELEASE_URL=$LATEST_RELEASE_URL" >> $GITHUB_OUTPUT
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_OUTPUT
          echo "$RELEASE_NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          echo "Latest Release URL: $LATEST_RELEASE_URL"
          echo "Release Notes: $RELEASE_NOTES"

      - name: Download the latest release
        run: |
          curl -L ${{ steps.fetch_release.outputs.LATEST_RELEASE_URL }} -o source.zip
          unzip source.zip
          rm source.zip

      - name: Create Archive
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'processed_release.zip'
          exclusions: '*.git* *.DS_Store'

      - name: List files for verification
        run: |
          ls -la

      - name: Print release notes
        run: |
          echo "Release Notes:"
          echo "${{ steps.fetch_release.outputs.RELEASE_NOTES }}"

      - name: Upload processed release as artifact
        uses: actions/upload-artifact@v2
        with:
          name: processed-release
          path: processed_release.zip
      
      - name: Get session token
        id: get_session_token
        env:
          ADOBE_API_URL: ${{ secrets.ADOBE_API_URL }}
          ADOBE_CLIENT_ID: ${{ secrets.ADOBE_CLIENT_ID }}
          ADOBE_CLIENT_SECRET: ${{ secrets.ADOBE_CLIENT_SECRET }}
        run: |
          response=$(curl -X POST \
          -u 'VKIMCVQ2ZN:78c24c7ab3ba4283b72859147dbbc73581fdf114' \
          -H 'Content-Type: application/json' \
          -d '{ "grant_type" : "session" }' \
          https://commercedeveloper-sandbox-api.adobe.com/rest/v1/app/session/token)
          
          echo "Session Token Response: $response"
          
          SESSION_TOKEN=$(echo $response | jq -r '.ust')
          echo "SESSION_TOKEN=$SESSION_TOKEN" >> $GITHUB_OUTPUT

      - name: Use session token to interact with Adobe Commerce API
        env:
          SESSION_TOKEN: ${{ steps.get_session_token.outputs.SESSION_TOKEN }}
        run: |
          # Example: Get system information
          response=$(curl -s -X GET \
          -H "Authorization: Bearer $SESSION_TOKEN" \
          -H "Content-Type: application/json" \
          "https://commercedeveloper-sandbox-api.adobe.com/rest/v1/system")
          
          echo "API Response:"
          echo "$response"
          
          # Check if the response is valid JSON
          if echo "$response" | jq empty; then
            echo "Valid JSON response:"
            echo "$response" | jq .
          else
            echo "Invalid JSON response. Raw output:"
            echo "$response"
          fi

      - name: Upload processed release to Adobe Commerce Marketplace
        env:
          SESSION_TOKEN: ${{ steps.get_session_token.outputs.SESSION_TOKEN }}
        run: |
          response=$(curl -X POST \
          -H "Authorization: Bearer $SESSION_TOKEN" \
          -H "Content-Type: application/zip" \
          --data-binary @processed_release.zip \
          "https://commercedeveloper-sandbox-api.adobe.com/rest/v1/files/file")
          
          echo "Upload Response:"
          echo "$response"
          
          # Check if the response is valid JSON
          if echo "$response" | jq empty; then
            echo "Valid JSON response:"
            echo "$response" | jq .
          else
            echo "Invalid JSON response. Raw output:"
            echo "$response"
          fi
          
          # Extract file_upload_id if present
          file_upload_id=$(echo "$response" | jq -r '.file_upload_id // empty')
          if [ ! -z "$file_upload_id" ]; then
            echo "File upload ID: $file_upload_id"
            echo "FILE_UPLOAD_ID=$file_upload_id" >> $GITHUB_OUTPUT
          else
            echo "File upload ID not found in the response."
          fi