name: Marketplace Automation

on:
  workflow_dispatch:
  push:
  release:
    types: [published]

jobs:
  marketplace-automation:
    runs-on: ubuntu-latest
    environment: internal 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # will work for live only
      - name: Extract Tag Name
        id: extract_tag
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "The tag name is $TAG_NAME"

      - name: Use the Tag Name
        run: |
          echo "Using the tag name: $TAG_NAME"

      - name: Fetch the latest release
        id: fetch_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          response=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/releases/latest")
          release_url=$(echo $response | jq -r '.zipball_url')
          release_notes=$(echo $response | jq -r '.body')
          release_tagname=$(echo $response | jq -r '.tag_name')

          # Remove 'v' prefix if it exists
          if [[ $release_tagname == v* ]]; then
            release_tagname=${release_tagname#v}
          fi
          
          echo "LATEST_RELEASE_URL=$release_url" >> $GITHUB_OUTPUT
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_OUTPUT
          echo "$release_notes" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "TAG_NAME=$release_tagname" >> $GITHUB_OUTPUT
          
          echo "Latest Release URL: $release_url"
          echo "Release Notes: $release_notes"
          echo "Tag name: $release_tagname"

      - name: Download the latest release
        run: |
          curl -L ${{ steps.fetch_release.outputs.LATEST_RELEASE_URL }} -o source.zip
          unzip source.zip
          rm source.zip

      - name: Create Archive
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'processed_release.zip'
          exclusions: '*.git* *.DS_Store'

      - name: List files for verification
        run: |
          ls -la

      - name: Upload processed release as artifact
        uses: actions/upload-artifact@v4
        with:
          name: processed-release
          path: processed_release.zip
          
      - name: Prepare the request payload
        run: |
          touch file-payload && \
          echo "--UNIQUE_BOUNDARY_TOKEN" > file-payload && \
          echo 'Content-Disposition: form-data; name="file[]"; filename="processed-release.zip"' >> file-payload && \
          echo 'Content-Type: application/zip' >> file-payload && \
          echo '' >> file-payload && \
          cat processed_release.zip >> file-payload && \
          echo '' >> file-payload && \
          echo "--UNIQUE_BOUNDARY_TOKEN--" >> file-payload
        
      - name: Get session token
        id: get_session_token
        env:
          BASE_URL: ${{ secrets.ADOBE_EQP_API_URL }}
          ADOBE_CLIENT_ID: ${{ secrets.ADOBE_CLIENT_ID }}
          ADOBE_CLIENT_SECRET: ${{ secrets.ADOBE_CLIENT_SECRET }}
        run: |
          response=$(curl -X POST \
          -u "${ADOBE_CLIENT_ID}:${ADOBE_CLIENT_SECRET}" \
          -H 'Content-Type: application/json' \
          -d '{ "grant_type" : "session" }' \
          ${BASE_URL}/rest/v1/app/session/token)

          SESSION_TOKEN=$(echo $response | jq -r '.ust')
          echo "SESSION_TOKEN=$SESSION_TOKEN" >> $GITHUB_OUTPUT
          
          echo "Session Token Response: $response"

      - name: Upload zip to adobe and get upload id
        id: upload_and_fetch
        env:
          SESSION_TOKEN: ${{ steps.get_session_token.outputs.SESSION_TOKEN }}
          BASE_URL: ${{ secrets.ADOBE_EQP_API_URL }}
        run: |
          # Upload the file
          upload_response=$(curl -X POST \
            -H "Authorization: Bearer $SESSION_TOKEN" \
             -H 'Content-Type: multipart/form-data; boundary=UNIQUE_BOUNDARY_TOKEN' \
             --data-binary @file-payload \
            "${BASE_URL}/rest/v1/files/uploads")
      
          # Check if the upload was successful
          if echo "$upload_response" | grep -q 'error'; then
            echo "Upload failed: $upload_response"
            exit 1
          else
            echo "Upload successful: $upload_response"
          fi
      
          # Extract upload ID from JSON response
          upload_id=$(echo $upload_response | jq -r '.[0].file_upload_id')

          echo "Upload ID: $upload_id"
          echo "FILE_UPLOAD_ID=$upload_id" >> $GITHUB_OUTPUT
          
      - name: Prepare JSON Payload
        run: |
          # Read the JSON template and replace placeholders with actual values
          sed "s/\${VERSION}/${VERSION}/g" .github/workflows/payload-template.json | sed "s/\${FILE_UPLOAD_ID}/${FILE_UPLOAD_ID}/g" > .github/workflows/payload.json
          
      - name: Submit the package
        env:
          SESSION_TOKEN: ${{ secrets.SESSION_TOKEN }}
          BASE_URL: ${{ secrets.ADOBE_EQP_API_URL }}
        run: |
          submission_response=$(curl -v -X POST \
            -H "Authorization: Bearer $SESSION_TOKEN" \
            -H "Content-Type: application/json" \
            --data @.github/workflows/payload.json \
            "${BASE_URL}/rest/v1/products/packages")

          echo "Submission Response:"
          echo "$submission_response"
          
